name: Deploy to EC2

on: 
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:

    docker:
      name: Containerization
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
                
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
                

        - name: Build and push docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ghcr.io/${{ github.repository_owner }}/react-app:${{github.sha}}


          


