name: Dependency Review

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          license-check: true
          vulnerability-check: true
          show-openssf-scorecard: true
          warn-on-openssf-scorecard-level: 3
