name: Trivy Security Scan

on: 
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  docker:
    name: Containerization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image (temporary)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/react-app:${{github.sha}}

  security-scan:
    name: Security Analysis with Trivy
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/react-app:${{github.sha}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


          


